# IMPORTS
# ---------------------------------------------------------------------------------------------------------------------#
from django.core.management.base import BaseCommand
from fact_book.models import Country, Currency, Continent, Region
import requests
from logging import getLogger


# IMPORTS
# ---------------------------------------------------------------------------------------------------------------------#
logger = getLogger('django')


# GLOBALS
# ---------------------------------------------------------------------------------------------------------------------#
COUNTRIES = {
    'AT': {'position': 1, 'display_name': "Austria"},
    'BE': {'position': 2, 'display_name': "Belgium"},
    'BG': {'position': 3, 'display_name': "Bulgaria"},
    'HR': {'position': 4, 'display_name': "Croatia"},
    'CY': {'position': 5, 'display_name': "Cyprus"},
    'CZ': {'position': 6, 'display_name': "Czech Republic"},
    'DK': {'position': 7, 'display_name': "Denmark"},
    'EE': {'position': 8, 'display_name': "Estonia"},
    'FI': {'position': 9, 'display_name': "Finland"},
    'FR': {'position': 10, 'display_name': "France"},
    'DE': {'position': 11, 'display_name': "Germany"},
    'GR': {'position': 12, 'display_name': "Greece"},
    'HU': {'position': 13, 'display_name': "Hungary"},
    'IE': {'position': 14, 'display_name': "Ireland"},
    'IT': {'position': 15, 'display_name': "Italy"},
    'LV': {'position': 16, 'display_name': "Latvia"},
    'LT': {'position': 17, 'display_name': "Lithuania"},
    'LU': {'position': 18, 'display_name': "Luxembourg"},
    'MT': {'position': 19, 'display_name': "Malta"},
    'NL': {'position': 20, 'display_name': "Netherlands"},
    'PL': {'position': 21, 'display_name': "Poland"},
    'PT': {'position': 22, 'display_name': "Portugal"},
    'RO': {'position': 23, 'display_name': "Romania"},
    'SK': {'position': 24, 'display_name': "Slovakia"},
    'SI': {'position': 25, 'display_name': "Slovenia"},
    'ES': {'position': 26, 'display_name': "Spain"},
    'SE': {'position': 27, 'display_name': "Sweden"},
    'GB': {'position': 28, 'display_name': "United Kingdom"},
    'AF': {'position': 29, 'display_name': "Afghanistan"},
    'AX': {'position': 30, 'display_name': "Åland Islands"},
    'AL': {'position': 31, 'display_name': "Albania"},
    'DZ': {'position': 32, 'display_name': "Algeria"},
    'AS': {'position': 33, 'display_name': "American Samoa"},
    'AD': {'position': 34, 'display_name': "Andorra"},
    'AO': {'position': 35, 'display_name': "Angola"},
    'AI': {'position': 36, 'display_name': "Anguilla"},
    'AQ': {'position': 37, 'display_name': "Antarctica"},
    'AG': {'position': 38, 'display_name': "Antigua and Barbuda"},
    'AR': {'position': 39, 'display_name': "Argentina"},
    'AM': {'position': 40, 'display_name': "Armenia"},
    'AW': {'position': 41, 'display_name': "Aruba"},
    'AU': {'position': 42, 'display_name': "Australia"},
    'AZ': {'position': 43, 'display_name': "Azerbaijan"},
    'BS': {'position': 44, 'display_name': "Bahamas"},
    'BH': {'position': 45, 'display_name': "Bahrain"},
    'BD': {'position': 46, 'display_name': "Bangladesh"},
    'BB': {'position': 47, 'display_name': "Barbados"},
    'BY': {'position': 48, 'display_name': "Belarus"},
    'BZ': {'position': 49, 'display_name': "Belize"},
    'BJ': {'position': 50, 'display_name': "Benin"},
    'BM': {'position': 51, 'display_name': "Bermuda"},
    'BT': {'position': 52, 'display_name': "Bhutan"},
    'BO': {'position': 53, 'display_name': "Bolivia"},
    'BQ': {'position': 54, 'display_name': "Bonaire, Sint Eustatius and Saba"},
    'BA': {'position': 55, 'display_name': "Bosnia and Herzegovina"},
    'BW': {'position': 56, 'display_name': "Botswana"},
    'BV': {'position': 57, 'display_name': "Bouvet Island"},
    'BR': {'position': 58, 'display_name': "Brazil"},
    'IO': {'position': 59, 'display_name': "British Indian Ocean Territory"},
    'BN': {'position': 60, 'display_name': "Brunei Darussalam"},
    'BF': {'position': 61, 'display_name': "Burkina Faso"},
    'BI': {'position': 62, 'display_name': "Burundi"},
    'CV': {'position': 63, 'display_name': "Cape Verde"},
    'KH': {'position': 64, 'display_name': "Cambodia"},
    'CM': {'position': 65, 'display_name': "Cameroon"},
    'CA': {'position': 66, 'display_name': "Canada"},
    'KY': {'position': 67, 'display_name': "Cayman Islands"},
    'CF': {'position': 68, 'display_name': "Central African Republic"},
    'TD': {'position': 69, 'display_name': "Chad"},
    'CL': {'position': 70, 'display_name': "Chile"},
    'CN': {'position': 71, 'display_name': "China"},
    'CX': {'position': 72, 'display_name': "Christmas Island"},
    'CC': {'position': 73, 'display_name': "Cocos (Keeling) Islands"},
    'CO': {'position': 74, 'display_name': "Colombia"},
    'KM': {'position': 75, 'display_name': "Comoros"},
    'CG': {'position': 76, 'display_name': "Congo"},
    'CD': {'position': 77, 'display_name': "Congo, the Democratic Republic of the"},
    'CK': {'position': 78, 'display_name': "Cook Islands"},
    'CR': {'position': 79, 'display_name': "Costa Rica"},
    'CI': {'position': 80, 'display_name': "Ivory Coast"},
    'CU': {'position': 81, 'display_name': "Cuba"},
    'CW': {'position': 82, 'display_name': "Curaçao"},
    'DJ': {'position': 83, 'display_name': "Djibouti"},
    'DM': {'position': 84, 'display_name': "Dominica"},
    'DO': {'position': 85, 'display_name': "Dominican Republic"},
    'EC': {'position': 86, 'display_name': "Ecuador"},
    'EG': {'position': 87, 'display_name': "Egypt"},
    'SV': {'position': 88, 'display_name': "El Salvador"},
    'GQ': {'position': 89, 'display_name': "Equatorial Guinea"},
    'ER': {'position': 90, 'display_name': "Eritrea"},
    'ET': {'position': 91, 'display_name': "Ethiopia"},
    'FK': {'position': 92, 'display_name': "Falkland Islands (Malvinas)"},
    'FO': {'position': 93, 'display_name': "Faroe Islands"},
    'FJ': {'position': 94, 'display_name': "Fiji"},
    'GF': {'position': 95, 'display_name': "French Guiana"},
    'PF': {'position': 96, 'display_name': "French Polynesia"},
    'TF': {'position': 97, 'display_name': "French Southern Territories"},
    'GA': {'position': 98, 'display_name': "Gabon"},
    'GM': {'position': 99, 'display_name': "Gambia"},
    'GE': {'position': 100, 'display_name': "Georgia"},
    'GH': {'position': 101, 'display_name': "Ghana"},
    'GI': {'position': 102, 'display_name': "Gibraltar"},
    'GL': {'position': 103, 'display_name': "Greenland"},
    'GD': {'position': 104, 'display_name': "Grenada"},
    'GP': {'position': 105, 'display_name': "Guadeloupe"},
    'GU': {'position': 106, 'display_name': "Guam"},
    'GT': {'position': 107, 'display_name': "Guatemala"},
    'GG': {'position': 108, 'display_name': "Guernsey"},
    'GN': {'position': 109, 'display_name': "Guinea"},
    'GW': {'position': 110, 'display_name': "Guinea-Bissau"},
    'GY': {'position': 111, 'display_name': "Guyana"},
    'HT': {'position': 112, 'display_name': "Haiti"},
    'HM': {'position': 113, 'display_name': "Heard Island and McDonald Islands"},
    'VA': {'position': 114, 'display_name': "Holy See (Vatican City State)"},
    'HN': {'position': 115, 'display_name': "Honduras"},
    'HK': {'position': 116, 'display_name': "Hong Kong"},
    'IS': {'position': 117, 'display_name': "Iceland"},
    'IN': {'position': 118, 'display_name': "India"},
    'ID': {'position': 119, 'display_name': "Indonesia"},
    'IR': {'position': 120, 'display_name': "Iran"},
    'IQ': {'position': 121, 'display_name': "Iraq"},
    'IM': {'position': 122, 'display_name': "Isle of Man"},
    'IL': {'position': 123, 'display_name': "Israel"},
    'JM': {'position': 124, 'display_name': "Jamaica"},
    'JP': {'position': 125, 'display_name': "Japan"},
    'JE': {'position': 126, 'display_name': "Jersey"},
    'JO': {'position': 127, 'display_name': "Jordan"},
    'KZ': {'position': 128, 'display_name': "Kazakhstan"},
    'KE': {'position': 129, 'display_name': "Kenya"},
    'KI': {'position': 130, 'display_name': "Kiribati"},
    'KP': {'position': 131, 'display_name': "Korea, Democratic People's Republic of"},
    'KR': {'position': 132, 'display_name': "Korea, Republic of"},
    'KW': {'position': 133, 'display_name': "Kuwait"},
    'KG': {'position': 134, 'display_name': "Kyrgyzstan"},
    'LA': {'position': 135, 'display_name': "Lao People's Democratic Republic"},
    'LB': {'position': 136, 'display_name': "Lebanon"},
    'LS': {'position': 137, 'display_name': "Lesotho"},
    'LR': {'position': 138, 'display_name': "Liberia"},
    'LY': {'position': 139, 'display_name': "Libya"},
    'LI': {'position': 140, 'display_name': "Liechtenstein"},
    'MO': {'position': 141, 'display_name': "Macao"},
    'MK': {'position': 142, 'display_name': "Macedonia"},
    'MG': {'position': 143, 'display_name': "Madagascar"},
    'MW': {'position': 144, 'display_name': "Malawi"},
    'MY': {'position': 145, 'display_name': "Malaysia"},
    'MV': {'position': 146, 'display_name': "Maldives"},
    'ML': {'position': 147, 'display_name': "Mali"},
    'MH': {'position': 148, 'display_name': "Marshall Islands"},
    'MQ': {'position': 149, 'display_name': "Martinique"},
    'MR': {'position': 150, 'display_name': "Mauritania"},
    'MU': {'position': 151, 'display_name': "Mauritius"},
    'YT': {'position': 152, 'display_name': "Mayotte"},
    'MX': {'position': 153, 'display_name': "Mexico"},
    'FM': {'position': 154, 'display_name': "Micronesia, Federated States of"},
    'MD': {'position': 155, 'display_name': "Moldova, Republic of"},
    'MC': {'position': 156, 'display_name': "Monaco"},
    'MN': {'position': 157, 'display_name': "Mongolia"},
    'ME': {'position': 158, 'display_name': "Montenegro"},
    'MS': {'position': 159, 'display_name': "Montserrat"},
    'MA': {'position': 160, 'display_name': "Morocco"},
    'MZ': {'position': 161, 'display_name': "Mozambique"},
    'MM': {'position': 162, 'display_name': "Myanmar"},
    'NA': {'position': 163, 'display_name': "Namibia"},
    'NR': {'position': 164, 'display_name': "Nauru"},
    'NP': {'position': 165, 'display_name': "Nepal"},
    'NC': {'position': 166, 'display_name': "New Caledonia"},
    'NZ': {'position': 167, 'display_name': "New Zealand"},
    'NI': {'position': 168, 'display_name': "Nicaragua"},
    'NE': {'position': 169, 'display_name': "Niger"},
    'NG': {'position': 170, 'display_name': "Nigeria"},
    'NU': {'position': 171, 'display_name': "Niue"},
    'NF': {'position': 172, 'display_name': "Norfolk Island"},
    'MP': {'position': 173, 'display_name': "Northern Mariana Islands"},
    'NO': {'position': 174, 'display_name': "Norway"},
    'OM': {'position': 175, 'display_name': "Oman"},
    'PK': {'position': 176, 'display_name': "Pakistan"},
    'PW': {'position': 177, 'display_name': "Palau"},
    'PS': {'position': 178, 'display_name': "Palestine, State of"},
    'PA': {'position': 179, 'display_name': "Panama"},
    'PG': {'position': 180, 'display_name': "Papua New Guinea"},
    'PY': {'position': 181, 'display_name': "Paraguay"},
    'PE': {'position': 182, 'display_name': "Peru"},
    'PH': {'position': 183, 'display_name': "Philippines"},
    'PN': {'position': 184, 'display_name': "Pitcairn"},
    'PR': {'position': 185, 'display_name': "Puerto Rico"},
    'QA': {'position': 186, 'display_name': "Qatar"},
    'RE': {'position': 187, 'display_name': "Réunion"},
    'RU': {'position': 188, 'display_name': "Russian Federation"},
    'RW': {'position': 189, 'display_name': "Rwanda"},
    'BL': {'position': 190, 'display_name': "Saint Barthélemy"},
    'SH': {'position': 191, 'display_name': "Saint Helena, Ascension and Tristan da Cunha"},
    'KN': {'position': 192, 'display_name': "Saint Kitts and Nevis"},
    'LC': {'position': 193, 'display_name': "Saint Lucia"},
    'MF': {'position': 194, 'display_name': "Saint Martin (French part)"},
    'PM': {'position': 195, 'display_name': "Saint Pierre and Miquelon"},
    'VC': {'position': 196, 'display_name': "Saint Vincent and the Grenadines"},
    'WS': {'position': 197, 'display_name': "Samoa"},
    'SM': {'position': 198, 'display_name': "San Marino"},
    'ST': {'position': 199, 'display_name': "Sao Tome and Principe"},
    'SA': {'position': 200, 'display_name': "Saudi Arabia"},
    'SN': {'position': 201, 'display_name': "Senegal"},
    'RS': {'position': 202, 'display_name': "Serbia"},
    'SC': {'position': 203, 'display_name': "Seychelles"},
    'SL': {'position': 204, 'display_name': "Sierra Leone"},
    'SG': {'position': 205, 'display_name': "Singapore"},
    'SX': {'position': 206, 'display_name': "Sint Maarten (Dutch part)"},
    'SB': {'position': 207, 'display_name': "Solomon Islands"},
    'SO': {'position': 208, 'display_name': "Somalia"},
    'ZA': {'position': 209, 'display_name': "South Africa"},
    'GS': {'position': 210, 'display_name': "South Georgia and the South Sandwich Islands"},
    'SS': {'position': 211, 'display_name': "South Sudan"},
    'LK': {'position': 212, 'display_name': "Sri Lanka"},
    'SD': {'position': 213, 'display_name': "Sudan"},
    'SR': {'position': 214, 'display_name': "Suriname"},
    'SJ': {'position': 215, 'display_name': "Svalbard and Jan Mayen"},
    'SZ': {'position': 216, 'display_name': "Swaziland"},
    'CH': {'position': 217, 'display_name': "Switzerland"},
    'SY': {'position': 218, 'display_name': "Syrian Arab Republic"},
    'TW': {'position': 219, 'display_name': "Taiwan, Province of China"},
    'TJ': {'position': 220, 'display_name': "Tajikistan"},
    'TZ': {'position': 221, 'display_name': "Tanzania, United Republic of"},
    'TH': {'position': 222, 'display_name': "Thailand"},
    'TL': {'position': 223, 'display_name': "Timor-Leste"},
    'TG': {'position': 224, 'display_name': "Togo"},
    'TK': {'position': 225, 'display_name': "Tokelau"},
    'TO': {'position': 226, 'display_name': "Tonga"},
    'TT': {'position': 227, 'display_name': "Trinidad and Tobago"},
    'TN': {'position': 228, 'display_name': "Tunisia"},
    'TR': {'position': 229, 'display_name': "Turkey"},
    'TM': {'position': 230, 'display_name': "Turkmenistan"},
    'TC': {'position': 231, 'display_name': "Turks and Caicos Islands"},
    'TV': {'position': 232, 'display_name': "Tuvalu"},
    'UG': {'position': 233, 'display_name': "Uganda"},
    'UA': {'position': 234, 'display_name': "Ukraine"},
    'AE': {'position': 235, 'display_name': "United Arab Emirates"},
    'US': {'position': 236, 'display_name': "United States"},
    'UM': {'position': 237, 'display_name': "United States Minor Outlying Islands"},
    'UY': {'position': 238, 'display_name': "Uruguay"},
    'UZ': {'position': 239, 'display_name': "Uzbekistan"},
    'VU': {'position': 240, 'display_name': "Vanuatu"},
    'VE': {'position': 241, 'display_name': "Venezuela, Bolivarian Republic of"},
    'VN': {'position': 242, 'display_name': "Vietnam"},
    'VG': {'position': 243, 'display_name': "Virgin Islands, British"},
    'VI': {'position': 244, 'display_name': "Virgin Islands, U.S."},
    'WF': {'position': 245, 'display_name': "Wallis and Futuna"},
    'EH': {'position': 246, 'display_name': "Western Sahara"},
    'YE': {'position': 247, 'display_name': "Yemen"},
    'ZM': {'position': 248, 'display_name': "Zambia"},
    'ZW': {'position': 249, 'display_name': "Zimbabwe"},
    'XK': {'position': 250, 'display_name': "Republic of Kosovo"},
}

CURRENCIES = {
    'ALL': {'symbol': 'Lek', 'name': 'Albania Lek'},
    'AFN': {'symbol': '؋', 'name': 'Afghanistan Afghani'},
    'ARS': {'symbol': '$', 'name': 'Argentina Peso'},
    'AWG': {'symbol': 'ƒ', 'name': 'Aruba Guilder'},
    'AUD': {'symbol': '$', 'name': 'Australia Dollar'},
    'AZN': {'symbol': 'ман', 'name': 'Azerbaijan New Manat'},
    'BSD': {'symbol': '$', 'name': 'Bahamas Dollar'},
    'BBD': {'symbol': '$', 'name': 'Barbados Dollar'},
    'BYR': {'symbol': 'p.', 'name': 'Belarus Ruble'},
    'BZD': {'symbol': 'BZ$', 'name': 'Belize Dollar'},
    'BMD': {'symbol': '$', 'name': 'Bermuda Dollar'},
    'BOB': {'symbol': '$b', 'name': 'Bolivia Boliviano'},
    'BAM': {'symbol': 'KM', 'name': 'Bosnia and Herzegovina Convertible Marka'},
    'BWP': {'symbol': 'P', 'name': 'Botswana Pula'},
    'BGN': {'symbol': 'лв', 'name': 'Bulgaria Lev'},
    'BRL': {'symbol': 'R$', 'name': 'Brazil Real'},
    'BND': {'symbol': '$', 'name': 'Brunei Darussalam Dollar'},
    'KHR': {'symbol': '៛', 'name': 'Cambodia Riel'},
    'CAD': {'symbol': '$', 'name': 'Canada Dollar'},
    'KYD': {'symbol': '$', 'name': 'Cayman Islands Dollar'},
    'CLP': {'symbol': '$', 'name': 'Chile Peso'},
    'CNY': {'symbol': '¥', 'name': 'China Yuan Renminbi'},
    'COP': {'symbol': '$', 'name': 'Colombia Peso'},
    'CRC': {'symbol': '₡', 'name': 'Costa Rica Colon'},
    'HRK': {'symbol': 'kn', 'name': 'Croatia Kuna'},
    'CUP': {'symbol': '₱', 'name': 'Cuba Peso'},
    'CZK': {'symbol': 'Kč', 'name': 'Czech Republic Koruna'},
    'DKK': {'symbol': 'kr', 'name': 'Denmark Krone'},
    'DOP': {'symbol': 'RD$', 'name': 'Dominican Republic Peso'},
    'XCD': {'symbol': '$', 'name': 'East Caribbean Dollar'},
    'EGP': {'symbol': '£', 'name': 'Egypt Pound'},
    'SVC': {'symbol': '$', 'name': 'El Salvador Colon'},
    'EEK': {'symbol': 'kr', 'name': 'Estonia Kroon'},
    'EUR': {'symbol': '€', 'name': 'Euro Member Countries'},
    'FKP': {'symbol': '£', 'name': 'Falkland Islands (Malvinas) Pound'},
    'FJD': {'symbol': '$', 'name': 'Fiji Dollar'},
    'GHC': {'symbol': '¢', 'name': 'Ghana Cedi'},
    'GIP': {'symbol': '£', 'name': 'Gibraltar Pound'},
    'GTQ': {'symbol': 'Q', 'name': 'Guatemala Quetzal'},
    'GGP': {'symbol': '£', 'name': 'Guernsey Pound'},
    'GYD': {'symbol': '$', 'name': 'Guyana Dollar'},
    'HNL': {'symbol': 'L', 'name': 'Honduras Lempira'},
    'HKD': {'symbol': '$', 'name': 'Hong Kong Dollar'},
    'HUF': {'symbol': 'Ft', 'name': 'Hungary Forint'},
    'ISK': {'symbol': 'kr', 'name': 'Iceland Krona'},
    'INR': {'symbol': '₹', 'name': 'India Rupee'},
    'IDR': {'symbol': 'Rp', 'name': 'Indonesia Rupiah'},
    'IRR': {'symbol': '﷼', 'name': 'Iran Rial'},
    'IMP': {'symbol': '£', 'name': 'Isle of Man Pound'},
    'ILS': {'symbol': '₪', 'name': 'Israel Shekel'},
    'JMD': {'symbol': 'J$', 'name': 'Jamaica Dollar'},
    'JPY': {'symbol': '¥', 'name': 'Japan Yen'},
    'JEP': {'symbol': '£', 'name': 'Jersey Pound'},
    'KZT': {'symbol': 'лв', 'name': 'Kazakhstan Tenge'},
    'KPW': {'symbol': '₩', 'name': 'Korea (North) Won'},
    'KRW': {'symbol': '₩', 'name': 'Korea (South) Won'},
    'KGS': {'symbol': 'лв', 'name': 'Kyrgyzstan Som'},
    'LAK': {'symbol': '₭', 'name': 'Laos Kip'},
    'LVL': {'symbol': 'Ls', 'name': 'Latvia Lat'},
    'LBP': {'symbol': '£', 'name': 'Lebanon Pound'},
    'LRD': {'symbol': '$', 'name': 'Liberia Dollar'},
    'LTL': {'symbol': 'Lt', 'name': 'Lithuania Litas'},
    'MKD': {'symbol': 'ден', 'name': 'Macedonia Denar'},
    'MYR': {'symbol': 'RM', 'name': 'Malaysia Ringgit'},
    'MUR': {'symbol': '₨', 'name': 'Mauritius Rupee'},
    'MXN': {'symbol': '$', 'name': 'Mexico Peso'},
    'MNT': {'symbol': '₮', 'name': 'Mongolia Tughrik'},
    'MZN': {'symbol': 'MT', 'name': 'Mozambique Metical'},
    'NAD': {'symbol': '$', 'name': 'Namibia Dollar'},
    'NPR': {'symbol': '₨', 'name': 'Nepal Rupee'},
    'ANG': {'symbol': 'ƒ', 'name': 'Netherlands Antilles Guilder'},
    'NZD': {'symbol': '$', 'name': 'New Zealand Dollar'},
    'NIO': {'symbol': 'C$', 'name': 'Nicaragua Cordoba'},
    'NGN': {'symbol': '₦', 'name': 'Nigeria Naira'},
    'NOK': {'symbol': 'kr', 'name': 'Norway Krone'},
    'OMR': {'symbol': '﷼', 'name': 'Oman Rial'},
    'PKR': {'symbol': '₨', 'name': 'Pakistan Rupee'},
    'PAB': {'symbol': 'B/.', 'name': 'Panama Balboa'},
    'PYG': {'symbol': 'Gs', 'name': 'Paraguay Guarani'},
    'PEN': {'symbol': 'S/.', 'name': 'Peru Nuevo Sol'},
    'PHP': {'symbol': '₱', 'name': 'Philippines Peso'},
    'PLN': {'symbol': 'zł', 'name': 'Poland Zloty'},
    'QAR': {'symbol': '﷼', 'name': 'Qatar Riyal'},
    'RON': {'symbol': 'lei', 'name': 'Romania New Leu'},
    'RUB': {'symbol': 'руб', 'name': 'Russia Ruble'},
    'SHP': {'symbol': '£', 'name': 'Saint Helena Pound'},
    'SAR': {'symbol': '﷼', 'name': 'Saudi Arabia Riyal'},
    'RSD': {'symbol': 'Дин.', 'name': 'Serbia Dinar'},
    'SCR': {'symbol': '₨', 'name': 'Seychelles Rupee'},
    'SGD': {'symbol': '$', 'name': 'Singapore Dollar'},
    'SBD': {'symbol': '$', 'name': 'Solomon Islands Dollar'},
    'SOS': {'symbol': 'S', 'name': 'Somalia Shilling'},
    'ZAR': {'symbol': 'R', 'name': 'South Africa Rand'},
    'LKR': {'symbol': '₨', 'name': 'Sri Lanka Rupee'},
    'SEK': {'symbol': 'kr', 'name': 'Sweden Krona'},
    'CHF': {'symbol': 'CHF', 'name': 'Switzerland Franc'},
    'SRD': {'symbol': '$', 'name': 'Suriname Dollar'},
    'SYP': {'symbol': '£', 'name': 'Syria Pound'},
    'TWD': {'symbol': 'NT$', 'name': 'Taiwan New Dollar'},
    'THB': {'symbol': '฿', 'name': 'Thailand Baht'},
    'TTD': {'symbol': 'TT$', 'name': 'Trinidad and Tobago Dollar'},
    'TRY': {'symbol': '₺', 'name': 'Turkey Lira'},
    'TVD': {'symbol': '$', 'name': 'Tuvalu Dollar'},
    'UAH': {'symbol': '₴', 'name': 'Ukraine Hryvnia'},
    'GBP': {'symbol': '£', 'name': 'United Kingdom Pound'},
    'USD': {'symbol': '$', 'name': 'United States Dollar'},
    'UYU': {'symbol': '$U', 'name': 'Uruguay Peso'},
    'UZS': {'symbol': 'лв', 'name': 'Uzbekistan Som'},
    'VEF': {'symbol': 'Bs', 'name': 'Venezuela Bolivar'},
    'VND': {'symbol': '₫', 'name': 'Vietnam Dong'},
    'YER': {'symbol': '﷼', 'name': 'Yemen Rial'},
    'ZWD': {'symbol': 'Z$', 'name': 'Zimbabwe Dollar'},
}

# COMMANDS
# ---------------------------------------------------------------------------------------------------------------------#
class Command(BaseCommand):
    help = "Sync FactBook with external APIs!"

    def handle(self, *args, **options):

        logger.info('Erasing data...')
        Country.objects.all().delete()
        Currency.objects.all().delete()
        # TODO: optionally clear all data...

        logger.info('Getting currency data...')
        # url = 'https://gist.githubusercontent.com/Fluidbyte/2973986/raw/' \
        #       '9ead0f85b6ee6071d018564fa5a314a0297212cc/Common-Currency.json'
        # response = requests.get(url)

        # for key, value in response.json().items():
        for key, value in CURRENCIES.items():
            logger.info(value)

            currency = Currency(
                name=value.get('name'),
                symbol=value.get('symbol'),
                code=key,
            )

            currency.save()

        logger.info('Getting country data...')
        response = requests.get('http://restcountries.eu/rest/v1/all')

        for data in response.json():
            logger.info(data.get('name'))
            continent, created = Continent.objects.get_or_create(name=data.get('region'))
            region, created = Region.objects.get_or_create(name=data.get('subregion'))

            try:
                country = Country.objects.get_by_natural_key(data.get(('name', )))
                logger.info('Found country, updating...')
                # TODO: Update the Country!

            except Country.DoesNotExist:
                country = Country(
                    name=data.get('name'),
                    alpha3code=data.get('alpha3Code'),
                    alpha2code=data.get('alpha2Code'),
                    continent=continent,
                    region=region,
                    population=data.get('population'),
                    demonym=data.get('demonym'),
                    native_name=data.get('nativeName'),
                )

                display_info = COUNTRIES.get(data.get('alpha2Code'))
                if display_info:
                    country.display_name = display_info.get('display_name')
                    country.position = display_info.get('position')
            finally:
                country.save()

        logger.info('Done')